CREATE TABLE IF NOT EXISTS admins(id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, password BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS rooms(
 id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'active',
 invite TEXT UNIQUE NOT NULL, ends_at INTEGER NOT NULL, closed_at INTEGER NOT NULL DEFAULT 0, delete_at INTEGER NOT NULL DEFAULT 0,
 retention INTEGER NOT NULL, created_at INTEGER NOT NULL, settings TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1,
 used INTEGER NOT NULL DEFAULT 0, reserved INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS participants(id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE, name TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, muted INTEGER NOT NULL DEFAULT 0, joined_at INTEGER NOT NULL, last_seen INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY, role TEXT NOT NULL, participant_id TEXT NOT NULL DEFAULT '', room_id TEXT NOT NULL DEFAULT '', expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS contents(id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE, author_id TEXT NOT NULL, author_name TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', filename TEXT NOT NULL DEFAULT '', mime TEXT NOT NULL DEFAULT '', bytes INTEGER NOT NULL DEFAULT 0, disk_bytes INTEGER NOT NULL DEFAULT 0, visible INTEGER NOT NULL DEFAULT 1, selected INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, payload TEXT NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS contents_room ON contents(room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS rooms_expiry ON rooms(state, delete_at);
CREATE TABLE IF NOT EXISTS ballots(poll_id TEXT NOT NULL REFERENCES contents(id) ON DELETE CASCADE, participant_id TEXT NOT NULL, choices TEXT NOT NULL, PRIMARY KEY(poll_id,participant_id));
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE, state TEXT NOT NULL, created_at INTEGER NOT NULL, error TEXT NOT NULL DEFAULT '', bytes INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY, room_id TEXT NOT NULL, action TEXT NOT NULL, actor TEXT NOT NULL, created_at INTEGER NOT NULL);
